### ISSUE TITLE
运行 gradle 脚本拉不起AS

### ISSUE THREAD

**Issue by lxb-symbol** [vSimpleton/RemoveButterKnife#1]
"  有需要的可以先直接拉代码运行，运行后会直接打开AS，选择自己要操作的项目即可。"  这一步就失败

**Comment by vSimpleton** [comment]
> " 有需要的可以先直接拉代码运行，运行后会直接打开AS，选择自己要操作的项目即可。" 这一步就失败

是用IDEA打开项目的吗？是的话改一下build.gradle.kts中intellij{}下的AS路径，我的是Mac，路径不一样
